
// This file is automatically generated

export const METADATA = {
  "name": "@razroo/agents-openai",
  "version": "0.0.13",
  "versions": {
    "@razroo/agents-openai": "0.0.13",
    "openai": "^5.10.1"
  }
};

export default METADATA;
