
// This file is automatically generated

export const METADATA = {
  "name": "@razroo/agents-realtime",
  "version": "0.0.13",
  "versions": {
    "@razroo/agents-realtime": "0.0.13"
  }
};

export default METADATA;
